project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with Quarto"
  navbar:
    title: Angelina
    right:
      - href: newtab.qmd
        text: Math 437 Project
        icon: megaphone
    tools: 
      - icon: github
        link: https://github.com/cunfucius
      
format:
  html:
    backgroundcolor: "#cfd8dc"
    fontcolor: "#37474f"
    linkcolor: "black"
    mainfont: "monospace"
    fontsize: 20px
    theme: [cosmo, styles.scss]
    
